### ISSUE TITLE
Error when trying to install

### ISSUE THREAD

**Issue by berlinddd** [zxllkada/Get-instagram-users-info---Any-instagram-account#11]
Traceback (most recent call last):
  File "instainfo_zxll.py", line 1, in <module>
    from PersonalLib.Total import JoinedWork as AgeDef
  File "/home/anony/Desktop/Tools/Info Gathering/Get-instagram-users-info---Any-instagram-account/zxllkada/Dump_Instagram_Information_ANY_ACCOUNT/PersonalLib/Total.py", line 3, in <module>
    from igql import InstagramGraphQL
ModuleNotFoundError: No module named 'igql'

**Comment by zxllkada** [comment]
pip install igql
